# Generated by Django 5.2.6 on 2025-10-11 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('campus_name', models.CharField(max_length=160, verbose_name='Nome do Campus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(verbose_name='Descrição do Problema')),
                ('priority', models.CharField(choices=[('LOW', 'Baixa'), ('MEDIUM', 'Média'), ('HIGH', 'Alta')], default='MEDIUM', max_length=10, verbose_name='Prioridade do Problema')),
                ('location', models.CharField(max_length=150, verbose_name='Localização do Problema')),
                ('report_type', models.CharField(choices=[('NULL', 'Não Informado'), ('HARDWARE', 'Hardware'), ('SOFTWARE', 'Software'), ('NETWORK', 'Rede'), ('ELECTRICAL', 'Elétrica'), ('CLIMATE', 'Climatização'), ('AUDIOVISUAL', 'Audiovisual'), ('FURNITURE', 'Mobília')], default='NULL', max_length=20, verbose_name='Tipo de Problema')),
                ('report_status', models.CharField(choices=[('OPEN', 'Aberto'), ('IN_PROGRESS', 'Em andamento'), ('RESOLVED', 'Resolvido'), ('CLOSED', 'Fechado')], default='OPEN', max_length=20, verbose_name='Status do Chamado')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='reports/attachments/', verbose_name='Anexo (opcional)')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Resolução')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.campus', verbose_name='Campus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('suap_username', models.CharField(max_length=50, unique=True, verbose_name='Enrollment Number')),
                ('suap_avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('suap_nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('suap_full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('suap_course', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('content', models.TextField(verbose_name='Comentário')),
                ('is_anonim', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='reports/comments/', verbose_name='Anexo (opcional)')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.report', verbose_name='Relatório')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_comments', to='core.userprofile', verbose_name='Usuário')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='report',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to='core.userprofile', verbose_name='Responsável pelo Atendimento'),
        ),
        migrations.AddField(
            model_name='report',
            name='report_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.userprofile', verbose_name='Usuário que reportou'),
        ),
    ]
