# Generated by Django 5.2.6 on 2025-10-19 22:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_reportcomment_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportcomment',
            options={'verbose_name': 'Comentário em Relatório', 'verbose_name_plural': 'Comentários em Relatórios'},
        ),
        migrations.AlterModelOptions(
            name='reportlike',
            options={'verbose_name': 'Curtida em Relatório', 'verbose_name_plural': 'Curtidas em Relatórios'},
        ),
        migrations.AlterUniqueTogether(
            name='reportlike',
            unique_together={('user', 'report')},
        ),
    ]
